// ==========================================
// 1. EVALUATION CORE DATASETS
// ==========================================
const assignments = [
    {
        title: "Assignment 01: Core Frontend Architecture",
        subject: "JavaScript DOM & Thread Logic",
        questions: [
            { question: "What does DOM stand for in web engineering frameworks?", options: ["Document Object Model", "Data Object Management", "Display Orientation Module", "Digital Object Model"], correctAnswer: 0 },
            { question: "Which standard method offers optimal performance when creating native DOM nodes?", options: ["document.makeElement()", "document.createElement()", "new HTMLElement()", "element.innerHTML"], correctAnswer: 1 },
            { question: "What is the computational primary axis purpose of CSS Flexbox structures?", options: ["1D structural execution & alignment mapping", "Database query serialization", "Complex hardware accelerated animations", "Global typography overriding"], correctAnswer: 0 },
            { question: "Which function clears browser heap allocation generated by 'setInterval' hooks?", options: ["stopInterval()", "pause()", "clearInterval()", "haltTimer()"], correctAnswer: 2 },
            { question: "Which explicit variable declaration keyword bypasses standard block-scoping constraints?", options: ["let", "const", "var", "All declarations maintain block-scope bounds"], correctAnswer: 2 }
        ]
    },
    {
        title: "Assignment 02: Relational Schema & Backend States",
        subject: "Database Management & Operations",
        questions: [
            { question: "What is the primary constraint responsibility of a Primary Key in relational schemas?", options: ["To isolate data deletions", "To strictly enforce unique row identification attributes", "To permit structural duplicate indices", "To systematically encrypt cell values"], correctAnswer: 1 },
            { question: "Which SQL clause is executed to isolate specific dataset segments from storage arrays?", options: ["EXTRACT", "GET", "SELECT", "OPEN"], correctAnswer: 2 },
            { question: "What middleware acts as the primary pipeline connecting Python runtime environments to MySQL targets?", options: ["Database Driver", "HTTP Ingress Controller", "Flat JSON Buffers", "Procedural CSS Configurations"], correctAnswer: 0 },
            { question: "What mechanism maps database normalization connections across independent entities?", options: ["Foreign Key constraints", "Hash cryptographic tables", "Linear execution latency spikes", "Null pointer exception layers"], correctAnswer: 0 },
            { question: "Which logical operation filters rows based on explicit operational conditions in standard SQL syntax?", options: ["GROUP BY", "WHERE", "ORDER BY", "HAVING"], correctAnswer: 1 }
        ]
    }
];

// ==========================================
// 2. STATE INTERFACE RUNTIME
// ==========================================
const state = {
    currentAssignmentIndex: 0,
    currentQuestionIndex: 0,
    score: 0,
    timeLeft: 15,
    timerId: null,
    selectedAnswer: null,
    history: []
};

// ==========================================
// 3. OBJECT INTERACTION DOM ENGINE
// ==========================================
const elements = {
    authModal: document.getElementById('auth-modal'),
    startScreen: document.getElementById('start-screen'),
    quizScreen: document.getElementById('quiz-screen'),
    resultScreen: document.getElementById('result-screen'),
    profileSidebar: document.getElementById('profile-sidebar'),
    
    authForm: document.getElementById('auth-form'),
    userNameInput: document.getElementById('user-fullname'),
    userEmailInput: document.getElementById('user-email'),
    
    sidebarName: document.getElementById('sidebar-name'),
    sidebarEmail: document.getElementById('sidebar-email'),
    avatarInitials: document.getElementById('avatar-initials'),
    assignmentTitle: document.getElementById('assignment-title'),
    metaSubject: document.getElementById('meta-subject'),
    
    startBtn: document.getElementById('start-btn'),
    nextBtn: document.getElementById('next-btn'),
    nextTaskBtn: document.getElementById('next-task-btn'),
    restartBtn: document.getElementById('restart-btn'),
    
    questionText: document.getElementById('question-text'),
    optionsContainer: document.getElementById('options-container'),
    currentQuestionNum: document.getElementById('current-question-num'),
    timeLeftDisplay: document.getElementById('time-left'),
    timerProgress: document.getElementById('timer-progress'),
    
    finalScoreDisplay: document.getElementById('final-score'),
    finalPercentageDisplay: document.getElementById('final-percentage'),
    performanceFeedback: document.getElementById('performance-feedback'),
    
    statAttempts: document.getElementById('stat-attempts'),
    statHigh: document.getElementById('stat-high'),
    chartPath: document.getElementById('chart-path'),
    chartDots: document.getElementById('chart-dots'),
    chartPlaceholder: document.getElementById('chart-placeholder')
};

// ==========================================
// 4. PORTAL FUNCTIONAL SYSTEMS
// ==========================================

elements.authForm.addEventListener('submit', function() {
    const name = elements.userNameInput.value.trim();
    const email = elements.userEmailInput.value.trim();
    
    if(!name || !email) return;

    // Cache to volatile current state memory session
    initPortal(name, email);
});

function initPortal(name, email) {
    elements.sidebarName.textContent = name;
    elements.sidebarEmail.textContent = email;
    
    const initials = name.split(" ").map(n => n[0]).join("").substring(0, 2);
    elements.avatarInitials.textContent = initials;
    
    // Close central overlay registration screen
    elements.authModal.classList.add('hidden');
    
    updateAnalytics();
    setupAssignmentMeta();
}

function setupAssignmentMeta() {
    const currentTask = assignments[state.currentAssignmentIndex];
    elements.assignmentTitle.textContent = currentTask.title;
    elements.metaSubject.textContent = currentTask.subject;
}

elements.startBtn.addEventListener('click', () => {
    elements.startScreen.classList.add('hidden');
    elements.quizScreen.classList.remove('hidden');
    state.currentQuestionIndex = 0;
    state.score = 0;
    loadQuestion();
});

function loadQuestion() {
    const activeQuestions = assignments[state.currentAssignmentIndex].questions;
    const currentData = activeQuestions[state.currentQuestionIndex];
    
    elements.currentQuestionNum.textContent = state.currentQuestionIndex + 1;
    elements.questionText.textContent = currentData.question;
    
    while (elements.optionsContainer.firstChild) {
        elements.optionsContainer.removeChild(elements.optionsContainer.firstChild);
    }
    
    currentData.options.forEach((optionText, index) => {
        const btn = document.createElement('button');
        btn.classList.add('option-btn');
        
        const textSpan = document.createElement('span');
        textSpan.textContent = optionText;
        
        const indicator = document.createElement('span');
        indicator.classList.add('indicator');
        indicator.textContent = String.fromCharCode(65 + index);
        
        btn.appendChild(textSpan);
        btn.appendChild(indicator);
        
        btn.addEventListener('click', () => selectAnswer(index));
        elements.optionsContainer.appendChild(btn);
    });
}

function selectAnswer(selectedIndex) {
    const allOptions = elements.optionsContainer.children;
    for (let i = 0; i < allOptions.length; i++) {
        allOptions[i].classList.remove('selected');
    }
    allOptions[selectedIndex].classList.add('selected');
    state.selectedAnswer = selectedIndex;
    elements.nextBtn.classList.remove('hidden');
}

elements.nextBtn.addEventListener('click', () => {
    const activeQuestions = assignments[state.currentAssignmentIndex].questions;
    const currentData = activeQuestions[state.currentQuestionIndex];
    
    if (state.selectedAnswer === currentData.correctAnswer) {
        state.score++;
    }
    
    state.currentQuestionIndex++;
    state.selectedAnswer = null;
    elements.nextBtn.classList.add('hidden');
    
    if (state.currentQuestionIndex < activeQuestions.length) {
        loadQuestion();
    } else {
        endQuiz();
    }
});

function endQuiz() {
    elements.quizScreen.classList.add('hidden');
    elements.resultScreen.classList.remove('hidden');
    
    const activeQuestions = assignments[state.currentAssignmentIndex].questions;
    const pct = Math.round((state.score / activeQuestions.length) * 100);
    
    elements.finalScoreDisplay.textContent = state.score + " / " + activeQuestions.length;
    elements.finalPercentageDisplay.textContent = pct + "%";
    
    if(pct >= 80) elements.performanceFeedback.textContent = "Excellent verification output. Performance matrix optimal.";
    else if(pct >= 60) elements.performanceFeedback.textContent = "Acceptable benchmark, code optimization recommended.";
    else elements.performanceFeedback.textContent = "Evaluation threshold unmet. Re-study operational guidelines.";
    
    state.history.push({ scorePercentage: pct });
    updateAnalytics();
    
    if (state.currentAssignmentIndex < assignments.length - 1) {
        elements.nextTaskBtn.classList.remove('hidden');
    } else {
        elements.nextTaskBtn.classList.add('hidden');
    }
}

// SVG LINE COORDINATE RESOLUTION ENGINE
function updateAnalytics() {
    const total = state.history.length;
    elements.statAttempts.textContent = total;
    
    if (total === 0) {
        elements.statHigh.textContent = "0%";
        elements.chartPlaceholder.classList.remove('hidden');
        return;
    }
    
    const highest = Math.max(...state.history.map(item => item.scorePercentage));
    elements.statHigh.textContent = highest + "%";
    elements.chartPlaceholder.classList.add('hidden');
    
    const paddingLeft = 20;
    const paddingRight = 280;
    const chartHeight = 120;
    
    let pathData = "";
    elements.chartDots.innerHTML = "";
    
    state.history.forEach((attempt, index) => {
        const x = total === 1 ? 150 : paddingLeft + (index / (total - 1)) * (paddingRight - paddingLeft);
        const y = 135 - (attempt.scorePercentage / 100) * chartHeight;
        
        if (index === 0) pathData += `M ${x} ${y}`;
        else pathData += ` L ${x} ${y}`;
        
        const circle = document.createElementNS("http://www.w3.org/2000/svg", "circle");
        circle.setAttribute("cx", x);
        circle.setAttribute("cy", y);
        circle.setAttribute("r", 5);
        circle.setAttribute("class", "chart-dot");
        
        elements.chartDots.appendChild(circle);
    });
    
    elements.chartPath.setAttribute("d", pathData);
}

elements.nextTaskBtn.addEventListener('click', () => {
    state.currentAssignmentIndex++;
    elements.resultScreen.classList.add('hidden');
    elements.startScreen.classList.remove('hidden');
    setupAssignmentMeta();
});

elements.restartBtn.addEventListener('click', () => {
    elements.resultScreen.classList.add('hidden');
    elements.startScreen.classList.remove('hidden');
});

// HARD FORCE REFRESH RESET (CRITICAL ALGORITHM)
window.addEventListener('DOMContentLoaded', () => {
    // Purging explicit browser storage data keys completely to force new lifecycle instantiation
    localStorage.removeItem('synapse_user_name');
    localStorage.removeItem('synapse_user_email');
    localStorage.removeItem('synapse_quiz_history');
    
    // Explicit runtime state defaults
    state.history = [];
    state.currentAssignmentIndex = 0;
    
    // System enforcement: Display registration overlay modal immediately on each single reload sequence
    elements.authModal.classList.remove('hidden');
});